---
name: "Build"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-node:
    uses: timmo001/workflows/.github/workflows/build-node-linux.yml@master
    with:
      additional-build-commands: |
        yarn build
      artifact-name: frontend-out
      artifact-path: out
  build-python:
    needs:
      - build-node
    uses: timmo001/workflows/.github/workflows/build-python-linux.yml@master
    with:
      additional-artifacts-name: frontend-out
      additional-artifacts-path: out
